<!DOCTYPE HERO[
<!ELEMENT HERO (START_MATCH, GG)>
<!ATTLIST HERO 
          name CDATA #REQUIRED>

<!ELEMENT START_MATCH (ABILITY | ULTIMATE | COOLDOWN | TEAM_UP | HP_CHECK | RESPAWN)*>

<!ELEMENT ABILITY (#PCDATA)>
<!ATTLIST ABILITY 
          target CDATA #IMPLIED>

<!ELEMENT ULTIMATE (#PCDATA)>

<!ELEMENT COOLDOWN (#PCDATA)>

<!ELEMENT TEAM_UP (ABILITY, ABILITY+)>

<!ELEMENT HP_CHECK (CONDITION, (ABILITY | ULTIMATE | STUN | RESPAWN)*)>
<!ELEMENT CONDITION (#PCDATA)>

<!ELEMENT RESPAWN (ABILITY | ULTIMATE | COOLDOWN | TEAM_UP | HP_CHECK | STUN)*>

<!ELEMENT STUN EMPTY>

<!ELEMENT GG EMPTY>
]>